FROM ubuntu
RUN apt-get update
RUN apt-get install python-software-properties build-essential -y
RUN add-apt-repository ppa:fkrull/deadsnakes -y
RUN apt-get update
RUN apt-get install python3.1 python3.1-dev -y
