FROM ubuntu
RUN apt-get update
RUN apt-get install python-software-properties build-essential -y
RUN add-apt-repository ppa:fkrull/deadsnakes -y
RUN apt-get update
RUN apt-get install python2.5 python2.5-dev -y
